# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6b218ef2921bad6f53bee202f907e00645f4035f90fd060aae45f2d1b2d09310914516de9f32e930e2a0cf7cb606826b0f74dbdaf582ca15b63aa240b0cfe266

test:
  secret_key_base: dd5384224458afad5f3a3c40f57d8c849abdeab5e6c97bec66ff3eb77039df7cc4505a3592862f4b2202e2e596934e5b36d17bf7f5329668609f29aa88b73f54

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
